### ISSUE TITLE
Step 2: top image

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/drum-star#12]
The first image is of the cymbal against the red curtain background. But you can’t get this venue until you’ve earned the first upgrade. So the image should include the snare drum and the next goal.

**Comment by libxx1** [comment]
I don't see that image, I see a bedroom with a question being asked.

**Comment by megwangrpf** [comment]
My bad - it's step 4, the 'first-upgrade.png' image at the top. There should be the cymbal and snare drum on the left, with the conga goal on the right, since you can only earn this background after you've upgraded and bought the snare drum.

**Comment by libxx1** [comment]
Oh wow good spot you're right. I've updated it now. There's no conga goal yet so the output at the end of the step is cymbal and snare drums bought, hidden button and chalkboard background.
