### ISSUE TITLE
Step 2: Lines 78 and 95

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/drum-star#14]
The outline box looks like it should only go around the Scratch block, not the yellow label boxes? Let me know so I can learn more about how we style/format the Scratch projects. Thank you!

**Comment by libxx1** [comment]
I can't see a way in Scratch blocks to highlight the block as being new without highlighting the attached comment. 

If you'd like to have a go, we use this to create the blocks of code. Putting a '+' at the beginning of the line puts that black border around it https://scratchblocks.github.io/#?style=scratch3&script=

**Comment by megwangrpf** [comment]
Cool. Thanks, Liz! I'll leave it to the experts (you).
