### ISSUE TITLE
Step 3: Line 102/103

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/drum-star#15]
It looks like the `set name to` block is from the previous step. Do we want to label the `set beats to 0` block to  “your variable” or “your new variable”?

**Comment by libxx1** [comment]
Yep the only additional block is the 'set beats' we don't need to label it as they've done it previously and we're not giving them any choices so it is clear without a comment. I've removed the comments from the previously added code in this task as they were only needed when introducing the new concept.
